export const DOLLAR_COMERCIAL_REQUEST_LOADING = 'DOLLAR_COMERCIAL_REQUEST_LOADING';
export const DOLLAR_COMERCIAL_REQUEST_SUCCESS = 'DOLLAR_COMERCIAL_REQUEST_SUCCESS';
export const DOLLAR_COMERCIAL_REQUEST_ERROR = 'DOLLAR_COMERCIAL_REQUEST_ERROR';